blog/urls.py
from django.conf import settings
from django.conf.urls import url,include,patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include("postss.urls",namespace='postss')),
    #url(r'^',include("posts.urls",namespace='posts')),
    #url(r'^posts', views.posthm),
    #url(r'^posts/$','posts.views.post_home'),
    #url(r'^posts/$', "<appname>.views.<functionname>"),	Direct Path to the function
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postss/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	homepage,
	aboutpage,
	postpage,
	contactpage,
    suc,
	) 

urlpatterns = [
    url(r'^$',homepage,name='home'),
    url(r'^about/$',aboutpage,name='about'),
    url(r'^post/$',postpage,name='post'),
    url(r'^contact/$',contactpage,name='contact'),
    url(r'^create/$',post_create,name="create"),
    url(r'^list/$',post_list,name='list'),
    #url(r'^create/$',post_create),
    url(r'^(?P<user_id>\d+)/$',postpage,name='detail'),
    #url(r'^(?P<user_id>\d+)/$',post_detail,name='detail'),
    url(r'^(?P<user_id>\d+)/edit$',post_update,name='update'),
    url(r'^(?P<user_id>\d+)/delete$',post_delete),
    url(r'^success/',suc,name="success"),
]

trydjango/urls.py
from django.conf import settings
from django.conf.urls import url,include,patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("postss.urls",namespace='postss')),
    #url(r'^',include("posts.urls",namespace='posts')),
    #url(r'^posts', views.posthm),
    #url(r'^posts/$','posts.views.post_home'),
    #url(r'^posts/$', "<appname>.views.<functionname>"),	Direct Path to the function
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf.urls import url,include
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	) 

urlpatterns = [
	url(r'^$',post_list,name='list'),
    url(r'^create/$',post_create),
    url(r'^(?P<id>\d+)/$',post_detail,name='detail'),
    url(r'^(?P<id>\d+)/edit$',post_update,name='update'),
    url(r'^(?P<id>\d+)/delete$',post_delete),
]

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    {% include "navigation.html" %}

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/about-bg.jpg' %});width:111.2%;margin-left:-6%">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">THINK <strong>DO</strong>  BE <strong>GET</strong> </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <h1>Hey! I am Reck</h1>
                <p>I am a Full Stack Developer at self learning pvt. ltd.</p>
                <p>Some of the qoutes I like...</p>
                <p>"The joy of coding Python should be in seeing short, concise, readable classes that express a lot of action in a small amount of clear code -- not in reams of trivial code that bores the reader to death." - <strong>
                Guido van Rossum</strong></p>
                <p> "When someone says: 'I want a programming language in which I need only say what I wish done', give him a lollipop." - <strong>
                Alan J. Perlis</strong></p>
                <p> "All the powers in the universe are already ours. It is we who have put our hands before our eyes and cry that it is dark."- <strong>
                Swami Vivekananda</strong></p>
                <p>Read Learn Share</p>
                <p>Get in touch</p>
                <h2><strong>See you...</strong></h2>
            </div>
        </div>
    </div>

    {% include "footer.html" %}
{% endblock content  %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>{% block head_title %}ReckBlog{% endblock head_title %}</title>
	<!-- Latest compiled and minified CSS -->

	<!-- CSS links -->
	<link rel="stylesheet" type="text/css" href='{% static "css/bootstrap.min.css" %}'>

	<!-- Optional theme -->
	<link rel="stylesheet" type="text/css" href='{% static "css/bootstrap-theme.min.css" %}'>


	<link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}'>
	
	<!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


	<style>{% block style %}{% endblock style %}</style>
</head>
<body>
	<!-- Facebook JS -->
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.6";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.6";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
	<!-- {% include "messages_display.html" %}
	 --><div class='container'>
		{% block content %}
				 
		{% endblock content  %}
	</div>
	<!-- <img src="{% static "img/venus.png"  %} alt="face" /> -->

	<!-- Latest compiled and minified JavaScript -->
	
	<!-- jQuery -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    {% include "navigation.html" %}

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/contact-bg.jpg' %});width:111.2%;margin-left:-6%">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form  id="contact_Form" action="{% url 'postss:contact' %}" method="post" role="form" style="display: block;" enctype='multipart/form-data' novalidate>{% csrf_token %}
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls" 
                        for="name" >
                            {{ form.name }}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls" 
                        for="emailid" >
                            {{ form.emailid }}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls" 
                        for="contact_no" >
                            {{ form.contact_no }}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls" 
                        for="message" >
                            {{ form.message }}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% include "footer.html" %}
{% endblock content  %}

templates/footer.html
    <!-- Footer -->
    <hr>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/RakeshGunduka" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/rakesh.gunduka" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/rakeshgunduka/bloggo" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; bloggo 2016</p>
                </div>
            </div>
        </div>
    </footer>

templates/form.html
<!DOCTYPE html -->
<!DOCTYPE html>
<html>
<head>
	<title>Reck</title>
</head>
<body>
	<h1>Form</h1>
		<form method='POST' action=''>{% csrf_token %}
			{{ form.as_p }} 
			<input type="submit" name="" value='Create Post'/>
		</form>
	</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    {% include "navigation.html" %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %});
        width:111.2%;margin-left:-6%" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Bloggo Blog</h1>
                        <hr class="small">
                        <span class="subheading">Read Learn Share</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            {% for obj in object_list %}
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-preview">
                        <!-- {% if obj.image %}
                            <img src="{{ obj.image.url }}" class="img-responsive "/>
                        {% endif %} -->
                        {% if obj.draft %}<h3>Draft</h3>{% endif %}
                        {% if obj.publish > today %}<h3>Future Post</h3>{% endif %}
                        <a href="{{ obj.get_absolute_url }}">
                            <h2 class="post-title">
                                {{ obj.title }}
                            <hr>
                            </h2>
                            <h3 class="post-subtitle">
                                {{ obj.subtitle }}
                            </h3>
                            <div class="col-sm-12">

                                <div class="content-markdown">{{ obj.content | truncatechars:150}}</div>
                            </div>
                            <small><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div></small>
                        </a>
                            <!-- <small>{{ obj.timestamp|timesince }}</small><br/> --></h3>
                        {% if obj.user.get_full_name %}
                            <p>Author: {{ obj.user.get_full_name }}</p>
                        {% endif %}
                        <p class="post-meta">Posted by 
                        <a href="">{{ User }}</a> 
                        on <small>{{ obj.publish }}</small></p>
                    </div>
                <hr>
                <!-- <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr> -->
                <!-- Pager -->
                
                <!-- <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul> -->
            </div>
            {% endfor %}
            <div class="pagination" style="margin-left:10%">
                    <span class="step-links">
                        {% if object_list.has_previous %}
                            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                        </span>

                        {% if object_list.has_next %}
                            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                        {% endif %}

                    </span>
                </div>
        </div>
    </div>
    {% include "footer.html" %}
{% endblock content  %}

templates/index.html
<!DOCTYPE html -->
<!DOCTYPE html>
<html>
<head>
	<title>Reck</title>
</head>
<body>
	<h1>{{title}} Hello there</h1>
	{% for obj in object_list %}
		<!-- <a href='/posts/{{ obj.id }}'>ID :{{ obj.id }}<br/></a> 
		<a href='{{ obj.get_absolute_url }}'>ID :{{ obj.id }}<br/></a>-->
		<a href='{% url "posts:detail"  id=obj.id %}'>ID :{{ obj.id }}<br/></a>
		<a>Title :{{ obj.title }}<br/></a>
		<a>Content :{{ obj.content }}<br/></a>
		<a>TimeStamp :{{ obj.timestamp }}<br/></a>
		<a>Updated TS:{{ obj.updated }}<br/></a>
	{% endfor %}
	</body>
</html>

templates/messages_display.html
{% if messages %}
 	<div class='col-sm-6 col-sm-offset-2'>
		{% for message in messages %}
			<div class="alert alert-warning" }}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
		    	{% if "html_safe" in message.tags %}{{ message|safe }}{% else  %}{{ message }}{% endif %}
		    	</li>
			</div>
		{% endfor %}
	</div>
{% endif %}

templates/navigation.html
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=='{% url "postss:home" %}'>Bloggo</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href='{% url "postss:home" %}'>Home</a>
                   </li>
                   <li>
                        <a href='{% url "postss:create" %}'>Add Post</a>
                   </li>
                    <li>
                        <a href="{% url 'postss:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'postss:post' %}">Sample Post</a>
                    </li>
                    <li>
                        <a href="{% url 'postss:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

templates/post.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    {% include "navigation.html" %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="
    background-image:url({% static 'img/post-bg.jpg' %});width:111.2%;margin-left:-6% "/>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-2 col-md-5 col-md-offset-2">
                   
                    <div class="post-heading ">
                            <h1>{{ instance.title }}</h1>
                            <h2 class="subheading">{{ instance.subtitle }}</h2>
                            <span class="meta">Posted by {{ instance.User}} on {{ instance.publish }}</span>
                    </div>
                </div>
                 <!-- 
                <div class="col-md-4 col-md-pull-2">
                    <div class="post-heading ">
                        {% if instance.image %}
                            <img src="{{ instance.image.url }}" class="img-responsive " style="max-width:80%;height:auto;"/>
                        {% endif %}
                    </div>
                </div> -->
            </div>
        </div>
    </header>
 
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
                    <div class="content-markdown">{{ instance.content }}</div>
                </div>
            </div>
        </div>
        <div class="fb-like col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
        <hr/>
        <div class="row ">
            <div class="col-sm-6 col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
            </div>
        </div>
    </article>
    {% include "footer.html" %}
{% endblock content  %}

templates/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load urlify %}
{% block head_title %}{{ instance.title }}|{{ block.super }}{% endblock head_title %}

<style>
{% block style %}
	h1 {
		color : #777777;
	}
{% endblock style %}
</style>


{% block content %}
	{% include "nav_others.html" %}
    

<div class='col-sm-6 col-sm-offset-3' style="margin-top:12%">
	{% if instance.image %}
		<img src="{{ instance.image.url }}" class="img-responsive" />
	{% endif %}
	<h1>{{title}}
	<small>{% if instance.draft %}<span style='color:red;'>Draft </span>{% endif %}{{ instance.publish }}</small></h1>
	{% if instance.user.get_full_name %}
	<p>Author: {{ instance.user.get_full_name }}</p>
	{% endif %}
	 
	<!-- {{ instance.content|truncatechars:10|urlify }}<br/>
	{{ share_string }}<br/>
 -->
	<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
	<hr/>
	<!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}/">
	Facebook
	</a>
	 -->
	<!-- <a href="https://twitter.com/home?status={{ instance.content|truncatechars:10|urlify }}%20{{ request.build_absolute_uri }}">
	Twitter
	</a>
	<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
	GooglePlus
	</a>
	<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{share_string}}&summary={{share_string}}&source={{ request.build_absolute_uri }}">
	Linkedin
	</a>
	<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{share_string}}">Share on Reddit</a> -->
	<div class="row">
		<div class="col-sm-12">
			<p>{{ instance.content | linebreaks | truncatechars:120}}</p>
		<hr/>
		</div>
		<div class="col-sm-6">
			<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
		</div>
	</div>
	<!--<p>ID :{{ instance.id }}<br/></p>
	<p>Title :{{ instance.title }}<br/></p>
	 <p>TimeStamp :{{ instance.timestamp }}<br/></p>
	<p>Updated TS:{{ instance.updated }}<br/></p> -->
</div>

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
{{ block.super  }}
{% include "nav_others.html" %}
<div class='col-sm-8 col-sm-offset-2' style="margin-top:10%">
	<h1>Add Post Details</h1>
	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
		{{ form.as_p}}
		<input class="btn btn-default" type="submit" name="" value='Create Post'/>
	</form>
</div>
<div style="margin-top:90%">
{% include "footer.html" %}
</div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<!-- <div class='col-sm-6'>
	<h1>{{title}} Hello there</h1>
		{% for obj in object_list %}
	 -->		<!-- <a href='/posts/{{ obj.id }}'>ID :{{ obj.id }}<br/></a> 
			<a href='{{ obj.get_absolute_url }}'>ID :{{ obj.id }}<br/></a>-->
			<!-- <a href='{% url "postss:detail"  id=obj.id %}'>{{ obj.title }}<br/></a>
			<p>Id :{{ obj.id }}<br/></p>
			<p>Content :{{ obj.content | linebreaks | truncatechars:120 }}<br/></p>
			<p>TimeStamp :{{ obj.timestamp }}<br/></p>
			<p>Updated TS:{{ obj.updated }}<br/></p>
		{% endfor %}
	</div> -->
	<div class='col-sm-6 col-sm-offset-3'>
		<h1>{{title}}</h1>
	<form method='GET' action=''>
		<input type='text' name='q' placeholder='Search posts'/>
		<input type='submit' value='Search'>
	</form>	
	{% for obj in object_list %}
		<div class="row">
			<div class="col-sm-10">
				<div class="thumbnail">
					{% if obj.image %}
						<img src="{{ obj.image.url }}" class="img-responsive "/>
				  	{% endif %}
				  	<div class="caption">
						{% if obj.draft %}<h3>Draft</h3>{% endif %}{% if obj.publish > today %}<h3>Future Post</h3>{% endif %}
						<h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a>
						<small>{{ obj.publish }}</small><br/>
						<!-- <small>{{ obj.timestamp|timesince }}</small><br/> --></h3>
					    {% if obj.user.get_full_name %}
							<p>Author: {{ obj.user.get_full_name }}</p>
						{% endif %}
					    <p>Content :{{ obj.content | linebreaks | truncatechars:120 }}<br/></p>
					    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button" >View</a> 
					    <!-- <a href="#" class="btn btn-default" role="button">Button</a> --></p>
				  </div>
				</div>
			</div>
			</hr>
		</div>
		<!-- {% cycle "" "<div class='col-sm-12'></hr></div>></div><div class='row'> " %}
		 -->
	{% endfor %}
	<div class="pagination">
	    <span class="step-links">
	        {% if object_list.has_previous %}
	            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
	        </span>

	        {% if object_list.has_next %}
	            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% endif %}">next</a>
	        {% endif %}

	    </span>
	</div>
	</div>

{% endblock content  %}